### ISSUE TITLE
as data format

### ISSUE THREAD

**Issue by whoizit** [gennyble/confindent#12]
This looks great, but I need same thing, but as data format where I don't know keys. Maybe you know an alternative? YAML not really what I need

**Comment by gennyble** [comment]
Do you want to be able to write data with this crate, too? Right now we only have a read API.

I don't know many alternatives. Maybe JSON would work?

For getting unknown keys with this crate:
I could make the `children` field on `Value` public which would let you look at all of a `Value`'s children and check their keys if you think that would be helpful.

**Comment by whoizit** [comment]
I think YAML is good for me. I just don't like the way YAML enumerates with -
for example in YAML:
```yaml
products:
  - product 1
  - product 2
```
but better way is 
```
products:
  product 1
  product 2
```

**Comment by whoizit** [comment]
looks good https://crates.io/crates/nccl
